<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Http\Resources\Json\ResourceCollection;

class TranslationResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id'         => $this->id,
            'group'      => $this->group,
            'locale'     => $this->locale,
            'key'        => $this->key,
            'value'      => $this->value,
            'tags'       => $this->tags,
        ];
    }

    public static function collection($resource)
    {
        return new TranslationResourceCollection($resource); // TODO: Change the autogenerated stub
    }
}
